Fix images
jverbraeken/Bachelorseminarium pull request #33
Opened 2018-04-10 14:12 UTC by jkatzy

2018-04-10 14:36 UTC, jverbraeken approved these changes

2018-04-10 14:42 UTC, Kloppie5 commented
Blocked by PR #32, which has requested changes

2018-04-10 15:07 UTC, mwolting commented
The architectural image contains both "architertures" (architectures) and "forrest" (forest)

2018-04-10 15:09 UTC, mwolting requested changes
general_system_bac_sem contains both "architertures" (architectures) and "forrest" (forest).

2018-04-12 12:41 UTC, mwolting approved these changes

2018-04-12 12:41 UTC, merged