Generic implementations
jverbraeken/Bachelorseminarium pull request #6
Opened 2018-03-13 11:57 UTC by jkatzy

2018-03-13 13:57 UTC, jverbraeken commented on Generic_implementations.tex
> +to have multiple servers with relatively small storage capacity each in clusters,
with a relatively small storage capacity and computational power

2018-03-13 14:05 UTC, jverbraeken requested changes
Generally looking good. However, I'm not sure if GFS is the main basis of existing Distributed Machine Learning frameworks. GFS is very much not open source, so that suggest that only Google could use Distributed Machine Learning.
Spark is definitely something that is used a lot in Distributed Machine Learning, however, Spark in itself cannot do any Machine Learning whatsoever.
According to http://www.pdl.cmu.edu/PDL-FTP/BigLearning/gaia.pdf the 3 state-of-the-art Distributed Machine Learning systems are

Bösen (J. Wei, W. Dai, A. Qiao, Q. Ho, H. Cui, G. R. Ganger, P. B. Gibbons, G. A. Gibson, and E. P. Xing, “Managed communication and consistency for fast data-parallel iterative analytics,” in SoCC, 2015.),

GeePS (H. Cui, H. Zhang, G. R. Ganger, P. B. Gibbons, and E. P. Xing, “GeePS: Scalable deep learning on distributed GPUs with a GPU-specialized parameter server,” in EuroSys, 2016, software available at https://github.com/cuihenggang/geeps)

and IterStore (H. Cui, A. Tumanov, J. Wei, L. Xu, W. Dai, J. Haber-Kucharsky, Q. Ho, G. R. Ganger, P. B. Gibbons, G. A. Gibson, and E. P. Xing, “Exploiting iterative-ness for parallel ML computations,” in SoCC, 2014, software available at https://github.com/cuihenggang/iterstore.)

2018-03-13 16:26 UTC, Kloppie5 commented on Generic_implementations.tex
> +that all map-reduce task are so similar to BSP tasks that, becuase BSP has a more theoretical
BECUASE

2018-03-13 16:27 UTC, Kloppie5 commented on Generic_implementations.tex
> +The GFS architecture that was desribed in their paper by google, was adapeted into
desribed, adapted, soluttion, ditributed

2018-03-13 16:29 UTC, Kloppie5 approved these changes
Maybe move the references to the bib file, but otherwise lgtm

2018-03-14 10:14 UTC, jverbraeken approved these changes

2018-03-15 12:00 UTC, merged